set_property PACKAGE_PIN W19 [get_ports B1]
set_property IOSTANDARD LVCMOS33 [get_ports B1] 
set_property PACKAGE_PIN T18 [get_ports B2] 
set_property IOSTANDARD LVCMOS33 [get_ports B2] 
set_property PACKAGE_PIN T17 [get_ports B3]
set_property IOSTANDARD LVCMOS33 [get_ports B3] 
set_property PACKAGE_PIN U17 [get_ports B4] 
set_property IOSTANDARD LVCMOS33 [get_ports B4]
set_property PACKAGE_PIN T1 [get_ports B5]
set_property IOSTANDARD LVCMOS33 [get_ports B5] 
set_property PACKAGE_PIN U1 [get_ports B6] 
set_property IOSTANDARD LVCMOS33 [get_ports B6]
set_property PACKAGE_PIN W2 [get_ports B7]
set_property IOSTANDARD LVCMOS33 [get_ports B7] 
set_property PACKAGE_PIN R3 [get_ports B8] 
set_property IOSTANDARD LVCMOS33 [get_ports B8]
set_property PACKAGE_PIN T2 [get_ports B9]
set_property IOSTANDARD LVCMOS33 [get_ports B9] 

#clock - set correctly
set_property PACKAGE_PIN W5 [get_ports clk1] 
set_property IOSTANDARD LVCMOS33 [get_ports clk1]

#reset - set correctly
set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst] 

#output
set_property PACKAGE_PIN W7 [get_ports {anodes[6]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[6]}]
set_property PACKAGE_PIN W6 [get_ports {anodes[5]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[5]}]
set_property PACKAGE_PIN U8 [get_ports {anodes[4]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[4]}]
set_property PACKAGE_PIN V8 [get_ports {anodes[3]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]
set_property PACKAGE_PIN U5 [get_ports {anodes[2]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property PACKAGE_PIN V5 [get_ports {anodes[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property PACKAGE_PIN U7 [get_ports {anodes[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]
set_property PACKAGE_PIN U2 [get_ports {enables[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {enables[0]}]
set_property PACKAGE_PIN U4 [get_ports {enables[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {enables[1]}]
set_property PACKAGE_PIN V4 [get_ports {enables[2]}]               
set_property IOSTANDARD LVCMOS33 [get_ports {enables[2]}]
set_property PACKAGE_PIN W4 [get_ports {enables[3]}]          
set_property IOSTANDARD LVCMOS33 [get_ports {enables[3]}]

set_property PACKAGE_PIN V7 [get_ports dc]                    
set_property IOSTANDARD LVCMOS33 [get_ports dc]
